var classes = [
    {
        "name": "Tests\\PileTableau",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "empty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "push",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pop",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "head",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "debug",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Tests\\Pile",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "implements": [
            "Tests\\Pile"
        ],
        "lcom": 1,
        "length": 28,
        "vocabulary": 14,
        "volume": 106.61,
        "difficulty": 6.75,
        "effort": 719.59,
        "level": 0.15,
        "bugs": 0.04,
        "time": 40,
        "intelligentContent": 15.79,
        "number_operators": 10,
        "number_operands": 18,
        "number_operators_unique": 6,
        "number_operands_unique": 8,
        "cloc": 32,
        "loc": 67,
        "lloc": 35,
        "mi": 95.59,
        "mIwoC": 51.72,
        "commentWeight": 43.88,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.58,
        "relativeSystemComplexity": 2.58,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 9.5,
        "totalSystemComplexity": 15.5,
        "package": "Tests\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Tests\\MarkdownMichelf",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "toHtml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Tests\\Markdown",
            "Michelf\\Markdown"
        ],
        "parents": [],
        "implements": [
            "Tests\\Markdown"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 76.82,
        "mIwoC": 76.82,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Tests\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Tests\\Math",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "maximum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "answer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toBase2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "multiplyByPowerOfTwo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "numberOf",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "qualify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 9,
        "ccnMethodMax": 5,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 6,
        "length": 100,
        "vocabulary": 35,
        "volume": 512.93,
        "difficulty": 17.48,
        "effort": 8965.09,
        "level": 0.06,
        "bugs": 0.17,
        "time": 498,
        "intelligentContent": 29.35,
        "number_operators": 33,
        "number_operands": 67,
        "number_operators_unique": 12,
        "number_operands_unique": 23,
        "cloc": 0,
        "loc": 51,
        "lloc": 51,
        "mi": 42.56,
        "mIwoC": 42.56,
        "commentWeight": 0,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.33,
        "relativeSystemComplexity": 6.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 38,
        "totalSystemComplexity": 38,
        "package": "Tests\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Tests\\Date",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "bissextile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lendemain",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 13,
        "ccnMethodMax": 13,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 107,
        "vocabulary": 32,
        "volume": 535,
        "difficulty": 10.22,
        "effort": 5467.7,
        "level": 0.1,
        "bugs": 0.18,
        "time": 304,
        "intelligentContent": 52.35,
        "number_operators": 34,
        "number_operands": 73,
        "number_operators_unique": 7,
        "number_operands_unique": 25,
        "cloc": 22,
        "loc": 75,
        "lloc": 53,
        "mi": 78.73,
        "mIwoC": 41.53,
        "commentWeight": 37.2,
        "kanDefect": 0.65,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Tests\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Tests\\MarkdownPandoc",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toHtml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Tests\\Markdown",
            "Exception"
        ],
        "parents": [],
        "implements": [
            "Tests\\Markdown"
        ],
        "lcom": 2,
        "length": 12,
        "vocabulary": 10,
        "volume": 39.86,
        "difficulty": 2.33,
        "effort": 93.01,
        "level": 0.43,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 17.08,
        "number_operators": 5,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 63.52,
        "mIwoC": 63.52,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Tests\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]